aliases:
  professor: "Professor"
  s-lecturer: "Senior Lecturer"
  ass-lecturer: "Associate Senior Lecturer"
  lecturer: "Lecturer"
  researcher: "Researcher"
  postdoc: "Postdoctoral Researcher"
  phd: "PhD student"
  visitor: "Visiting Researcher"
  affiliate: "Affiliate member"
  past: "Past member"

